image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew

build_script:
  - ./gradlew --version
  - ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info || (
    echo "Retry in 5s due to network hiccup" && sleep 5 &&
    ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info
    )