image: Ubuntu2204
stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8"

install:

  - sudo apt-get update -y
  - sudo apt-get install -y ca-certificates ca-certificates-java curl
  - sudo update-ca-certificates -f
  - sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure


  - curl -I https://repo.maven.apache.org/maven2/ || true


  - chmod +x gradlew
  - ./gradlew --version

build_script:

  - ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info || (
    echo "Retry in 5s due to network hiccup" && sleep 5 &&
    ./gradlew test --no-daemon --refresh-dependencies --stacktrace --info
    )